classdef MultiBandModulator < audioPlugin
% Experimentální zvukový efekt založený na dynamické filtraci signálu
% Semestrální práce
% Bc. David Leitgeb
% zimní semestr 2023/2024
    properties
        % Základní parametry efektu
        PluginInputGain = 0;
        PluginOutputGain = 0;
        PluginMix = 100;
        PluginBPM = 140;
        PluginClearBuffers = false;

        % Parametry jednotlivých pásem:
        % Přímá větev:
        DirectEnable = true;
        DirectPan = 0;
        DirectGain = 0;

        % Pásmo 1                           % Pásmo 2                           % Pásmo 3                           % Pásmo 4                           % Pásmo 5
        Band1Enable = true;                 Band2Enable = false;                Band3Enable = false;                Band4Enable = false;                Band5Enable = false;         
        Band1FilterType = 'BP';             Band2FilterType = 'BP';             Band3FilterType = 'BP';             Band4FilterType = 'BP';             Band5FilterType = 'BP';
        Band1FilterCutoff = 1000;           Band2FilterCutoff = 1000;           Band3FilterCutoff = 1000;           Band4FilterCutoff = 1000;           Band5FilterCutoff = 1000;  
        Band1FilterQ = 0.71;                Band2FilterQ = 0.71;                Band3FilterQ = 0.71;                Band4FilterQ = 0.71;                Band5FilterQ = 0.71;
        Band1FilterGain = 0;                Band2FilterGain = 0;                Band3FilterGain = 0;                Band4FilterGain = 0;                Band5FilterGain = 0;
        Band1FilterOrder = '2';             Band2FilterOrder = '2';             Band3FilterOrder = '2';             Band4FilterOrder = '2';             Band5FilterOrder = '2';
        Band1Pan = 0;                       Band2Pan = 0;                       Band3Pan = 0;                       Band4Pan = 0;                       Band5Pan = 0;
        Band1Gain = 0;                      Band2Gain = 0;                      Band3Gain = 0;                      Band4Gain = 0;                      Band5Gain = 0;
        Band1Delay = 1;                     Band2Delay = 1;                     Band3Delay = 1;                     Band4Delay = 1;                     Band5Delay = 1;
        Band1Feedback = 0;                  Band2Feedback = 0;                  Band3Feedback = 0;                  Band4Feedback = 0;                  Band5Feedback = 0;
        Band1Feedforward = 100;             Band2Feedforward = 100;             Band3Feedforward = 100;             Band4Feedforward = 100;             Band5Feedforward = 100;

        % Nízkofrekvenční oscilátory
        % LFO 1                             % LFO 2
        LFO1Shape = 'SIN';                  LFO2Shape = 'SIN';
        LFO1RateHz = 1;                     LFO2RateHz = 1;
        LFO1RateSync = '1/4';               LFO2RateSync = '1/4';
        LFO1RateType = 'Hz';                LFO2RateType = 'Hz';
        LFO1Depth = 100;                    LFO2Depth = 100;
        LFO1Phase = 0;                      LFO2Phase = 0;
        LFO1NoiseIndex = 0;                 LFO2NoiseIndex = 0;
        LFO1NoiseValue = 0;                 LFO2NoiseValue = 0;

        % Modulace
        % Přímá větev
        ModDirectLFO1Pan = 0;
        ModDirectLFO2Pan = 0;
        % Pásmo 1                           % Pásmo 2                           % Pásmo 3                           % Pásmo 4                           % Pásmo 5
        ModB1LFO1Cutoff = 0;                ModB2LFO1Cutoff = 0;                ModB3LFO1Cutoff = 0;                ModB4LFO1Cutoff = 0;                ModB5LFO1Cutoff = 0;
        ModB1LFO2Cutoff = 0;                ModB2LFO2Cutoff = 0;                ModB3LFO2Cutoff = 0;                ModB4LFO2Cutoff = 0;                ModB5LFO2Cutoff = 0;
        ModB1LFO1Pan = 0;                   ModB2LFO1Pan = 0;                   ModB3LFO1Pan = 0;                   ModB4LFO1Pan = 0;                   ModB5LFO1Pan = 0;
        ModB1LFO2Pan = 0;                   ModB2LFO2Pan = 0;                   ModB3LFO2Pan = 0;                   ModB4LFO2Pan = 0;                   ModB5LFO2Pan = 0;
        ModB1LFO1Delay = 0;                 ModB2LFO1Delay = 0;                 ModB3LFO1Delay = 0;                 ModB4LFO1Delay = 0;                 ModB5LFO1Delay = 0;
        ModB1LFO2Delay = 0;                 ModB2LFO2Delay = 0;                 ModB3LFO2Delay = 0;                 ModB4LFO2Delay = 0;                 ModB5LFO2Delay = 0;
        % Rozsahy modulace
        ModCutoffRange = 10;
        ModDelayRange = 5;

        % Zpožďovací linka
        Band1Buffer = zeros(getSampleRate(audioPlugin) * 2, 2);
        Band2Buffer = zeros(getSampleRate(audioPlugin) * 2, 2);
        Band3Buffer = zeros(getSampleRate(audioPlugin) * 2, 2);
        Band4Buffer = zeros(getSampleRate(audioPlugin) * 2, 2);
        Band5Buffer = zeros(getSampleRate(audioPlugin) * 2, 2);
        Band1Dpw = 1;
        Band2Dpw = 1;
        Band3Dpw = 1;
        Band4Dpw = 1;
        Band5Dpw = 1;

        % Filtrace
        Band1FilterConditions = zeros(2, 2);
        Band2FilterConditions = zeros(2, 2);
        Band3FilterConditions = zeros(2, 2);
        Band4FilterConditions = zeros(2, 2);
        Band5FilterConditions = zeros(2, 2);

    end
    properties (Constant)
        PluginInterface = audioPluginInterface( ...
                                    'InputChannels',2,...
                                    'OutputChannels',2,...
                                    'PluginName','MultiBandModulator',...
                                    'VendorName','David Leitgeb', ...
                                    'VendorVersion','1.0.0', ...
            audioPluginGridLayout('RowHeight',[20 75 20 75 20 75 20 75 20 75 20 75 20 75 20 20 75 20 75], 'ColumnWidth',[100 100 100 100 100 100 100 100 100 100 100 40 100 100 100 100 100 100],    'RowSpacing',5,    'ColumnSpacing',5, 'Padding',[20 20 20 20]),...
            ... % Základní parametry efektu
            audioPluginParameter('PluginInputGain',             'DisplayName', 'Input Gain',                'Layout',[2,1],      'Label','dB',      'Mapping',{'pow',1/3, -64, 24},                                 'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('PluginOutputGain',            'DisplayName', 'Output Gain',               'Layout',[2,2],      'Label','dB',      'Mapping',{'pow',1/3, -64, 24},                                 'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('PluginMix',                   'DisplayName', 'Mix',                       'Layout',[2,3],      'Label','%',       'Mapping',{'int',0,100},                                        'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('PluginBPM',                   'DisplayName', 'BPM',                       'Layout',[2,4],      'Label','',        'Mapping',{'int',20, 200},                                      'DisplayNameLocation', 'Above',     'Style', 'hslider'),...    
            audioPluginParameter('PluginClearBuffers',          'DisplayName', 'Clear Buffers',             'Layout',[2,5],      'Label','',                                                                        'DisplayNameLocation', 'Above',     'Style', 'vtoggle'),...
            ... % Přímá větev 
            audioPluginParameter('DirectEnable',                'DisplayName', 'Direct',                    'Layout',[4,1],      'Label','',                                                                        'DisplayNameLocation', 'Above',     'Style', 'checkbox'),...
            audioPluginParameter('DirectPan',                   'DisplayName', 'Pan',                       'Layout',[4,7],      'Label','',        'Mapping',{'lin',-50, 50},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('DirectGain',                  'DisplayName', 'Gain',                      'Layout',[4,11],      'Label','dB',      'Mapping',{'pow',1/3, -64, 24},                                 'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Pásmo 1
            audioPluginParameter('Band1Enable',                 'DisplayName', 'Band 1',                    'Layout',[6,1],      'Label','',                                                                        'DisplayNameLocation', 'Above',     'Style', 'checkbox'),...
            audioPluginParameter('Band1FilterType',             'DisplayName', 'Filter Type',               'Layout',[6,2],      'Label','',        'Mapping',{'enum','HP','LS','BP', 'BR','P','HS','LP', 'None'},  'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band1FilterCutoff',           'DisplayName', 'Cutoff',                    'Layout',[6,3],      'Label','Hz',      'Mapping',{'log', 10, 22000},                                   'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band1FilterQ',                'DisplayName', 'Q',                         'Layout',[6,4],      'Label','',        'Mapping',{'lin', 0.10, 18},                                    'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band1FilterGain',             'DisplayName', 'Filter Gain',               'Layout',[6,5],      'Label','dB',      'Mapping',{'lin',-15,15},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band1FilterOrder',            'DisplayName', 'Order (HP, LP)',            'Layout',[6,6],      'Label','',        'Mapping',{'enum','1', '2'},                                    'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band1Pan',                    'DisplayName', 'Pan',                       'Layout',[6,7],      'Label','',        'Mapping',{'lin',-50, 50},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band1Delay',                  'DisplayName', 'Delay',                     'Layout',[6,8],      'Label','ms',      'Mapping',{'log', 1, 1000},                                     'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band1Feedback',               'DisplayName', 'Feedback',                  'Layout',[6,9],      'Label','%',       'Mapping',{'lin', 0, 95},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band1Feedforward',            'DisplayName', 'Feedforward',               'Layout',[6,10],     'Label','%',       'Mapping',{'lin', 0, 100},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band1Gain',                   'DisplayName', 'Gain',                      'Layout',[6,11],     'Label','dB',      'Mapping',{'pow',1/3, -64, 24},                                 'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Pásmo 2
            audioPluginParameter('Band2Enable',                 'DisplayName', 'Band 2',                    'Layout',[8,1],      'Label','',                                                                        'DisplayNameLocation', 'Above',     'Style', 'checkbox'),...
            audioPluginParameter('Band2FilterType',             'DisplayName', 'Filter Type',               'Layout',[8,2],      'Label','',        'Mapping',{'enum','HP','LS','BP', 'BR','P','HS','LP', 'None'},  'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band2FilterCutoff',           'DisplayName', 'Cutoff',                    'Layout',[8,3],      'Label','Hz',      'Mapping',{'log', 10, 22000},                                   'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band2FilterQ',                'DisplayName', 'Q',                         'Layout',[8,4],      'Label','',        'Mapping',{'lin', 0.10, 18},                                    'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band2FilterGain',             'DisplayName', 'Filter Gain',               'Layout',[8,5],      'Label','dB',      'Mapping',{'lin',-15,15},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band2FilterOrder',            'DisplayName', 'Order (HP, LP)',            'Layout',[8,6],      'Label','',        'Mapping',{'enum','1', '2'},                                    'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band2Pan',                    'DisplayName', 'Pan',                       'Layout',[8,7],      'Label','',        'Mapping',{'lin',-50, 50},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band2Delay',                  'DisplayName', 'Delay',                     'Layout',[8,8],      'Label','ms',      'Mapping',{'log', 1, 1000},                                     'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band2Feedback',               'DisplayName', 'Feedback',                  'Layout',[8,9],      'Label','%',       'Mapping',{'lin', 0, 95},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band2Feedforward',            'DisplayName', 'Feedforward',               'Layout',[8,10],     'Label','%',       'Mapping',{'lin', 0, 100},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band2Gain',                   'DisplayName', 'Gain',                      'Layout',[8,11],     'Label','dB',      'Mapping',{'pow',1/3, -64, 24},                                 'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Pásmo 3
            audioPluginParameter('Band3Enable',                 'DisplayName', 'Band 3',                    'Layout',[10,1],     'Label','',                                                                        'DisplayNameLocation', 'Above',     'Style', 'checkbox'),...
            audioPluginParameter('Band3FilterType',             'DisplayName', 'Filter Type',               'Layout',[10,2],     'Label','',        'Mapping',{'enum','HP','LS','BP', 'BR','P','HS','LP', 'None'},  'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band3FilterCutoff',           'DisplayName', 'Cutoff',                    'Layout',[10,3],     'Label','Hz',      'Mapping',{'log', 10, 22000},                                   'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band3FilterQ',                'DisplayName', 'Q',                         'Layout',[10,4],     'Label','',        'Mapping',{'lin', 0.10, 18},                                    'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band3FilterGain',             'DisplayName', 'Filter Gain',               'Layout',[10,5],     'Label','dB',      'Mapping',{'lin',-15,15},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band3FilterOrder',            'DisplayName', 'Order (HP, LP)',            'Layout',[10,6],     'Label','',        'Mapping',{'enum','1', '2'},                                    'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band3Pan',                    'DisplayName', 'Pan',                       'Layout',[10,7],     'Label','',        'Mapping',{'lin',-50, 50},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band3Delay',                  'DisplayName', 'Delay',                     'Layout',[10,8],     'Label','ms',      'Mapping',{'log', 1, 1000},                                     'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band3Feedback',               'DisplayName', 'Feedback',                  'Layout',[10,9],     'Label','%',       'Mapping',{'lin', 0, 95},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band3Feedforward',            'DisplayName', 'Feedforward',               'Layout',[10,10],    'Label','%',       'Mapping',{'lin', 0, 100},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band3Gain',                   'DisplayName', 'Gain',                      'Layout',[10,11],    'Label','dB',      'Mapping',{'pow',1/3, -64, 24},                                 'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Pásmo 4
            audioPluginParameter('Band4Enable',                 'DisplayName', 'Band 4',                    'Layout',[12,1],     'Label','',                                                                        'DisplayNameLocation', 'Above',     'Style', 'checkbox'),...
            audioPluginParameter('Band4FilterType',             'DisplayName', 'Filter Type',               'Layout',[12,2],     'Label','',        'Mapping',{'enum','HP','LS','BP', 'BR','P','HS','LP', 'None'},  'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band4FilterCutoff',           'DisplayName', 'Cutoff',                    'Layout',[12,3],     'Label','Hz',      'Mapping',{'log', 10, 22000},                                   'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band4FilterQ',                'DisplayName', 'Q',                         'Layout',[12,4],     'Label','',        'Mapping',{'lin', 0.10, 18},                                    'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band4FilterGain',             'DisplayName', 'Filter Gain',               'Layout',[12,5],     'Label','dB',     'Mapping',{'lin',-15,15},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band4FilterOrder',            'DisplayName', 'Order (HP, LP)',            'Layout',[12,6],     'Label','',        'Mapping',{'enum','1', '2'},                                    'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band4Pan',                    'DisplayName', 'Pan',                       'Layout',[12,7],     'Label','',        'Mapping',{'lin',-50, 50},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band4Delay',                  'DisplayName', 'Delay',                     'Layout',[12,8],     'Label','ms',      'Mapping',{'log', 1, 1000},                                     'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band4Feedback',               'DisplayName', 'Feedback',                  'Layout',[12,9],     'Label','%',       'Mapping',{'lin', 0, 95},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band4Feedforward',            'DisplayName', 'Feedforward',               'Layout',[12,10],    'Label','%',       'Mapping',{'lin', 0, 100},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band4Gain',                   'DisplayName', 'Gain',                      'Layout',[12,11],    'Label','dB',      'Mapping',{'pow',1/3, -64, 24},                                 'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Pásmo 5
            audioPluginParameter('Band5Enable',                 'DisplayName', 'Band 5',                    'Layout',[14,1],     'Label','',                                                                        'DisplayNameLocation', 'Above',     'Style', 'checkbox'),...
            audioPluginParameter('Band5FilterType',             'DisplayName', 'Filter Type',               'Layout',[14,2],     'Label','',        'Mapping',{'enum','HP','LS','BP', 'BR','P','HS','LP', 'None'},  'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band5FilterCutoff',           'DisplayName', 'Cutoff',                    'Layout',[14,3],     'Label','Hz',      'Mapping',{'log', 10, 22000},                                   'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band5FilterQ',                'DisplayName', 'Q',                         'Layout',[14,4],     'Label','',        'Mapping',{'lin', 0.10, 18},                                    'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band5FilterGain',             'DisplayName', 'Filter Gain',               'Layout',[14,5],     'Label','dB',      'Mapping',{'lin',-15,15},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band5FilterOrder',            'DisplayName', 'Order (HP, LP)',            'Layout',[14,6],     'Label','',        'Mapping',{'enum','1', '2'},                                    'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('Band5Pan',                    'DisplayName', 'Pan',                       'Layout',[14,7],     'Label','',        'Mapping',{'lin',-50, 50},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band5Delay',                  'DisplayName', 'Delay',                     'Layout',[14,8],     'Label','ms',      'Mapping',{'log', 1, 1000},                                     'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band5Feedback',               'DisplayName', 'Feedback',                  'Layout',[14,9],     'Label','%',       'Mapping',{'lin', 0, 95},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band5Feedforward',            'DisplayName', 'Feedforward',               'Layout',[14,10],    'Label','%',       'Mapping',{'lin', 0, 100},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('Band5Gain',                   'DisplayName', 'Gain',                      'Layout',[14,11],    'Label','dB',      'Mapping',{'pow',1/3, -64, 24},                                 'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Nízkofrekvenční oscilátory
            ... % LFO 1
            audioPluginParameter('LFO1Shape',                   'DisplayName', 'LFO1 Shape',                'Layout',[17,1],     'Label','',        'Mapping',{'enum','SIN', 'TRI', 'SQR', 'SAW', 'S&H'},           'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('LFO1RateHz',                  'DisplayName', 'Rate',                      'Layout',[17,2],     'Label','Hz',      'Mapping',{'log', 0.01, 20},                                    'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('LFO1RateSync',                'DisplayName', 'Rate',                      'Layout',[17,3],     'Label','',        'Mapping',{'enum','1', '1/2', '1/4', '1/8', '1/16', '1/32'},    'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('LFO1RateType',                'DisplayName', 'Time Mode',                 'Layout',[17,4],     'Label','',        'Mapping',{'enum','Sync', 'Hz'},                                'DisplayNameLocation', 'Above',     'Style', 'vtoggle'),...
            audioPluginParameter('LFO1Depth',                   'DisplayName', 'Depth',                     'Layout',[17,5],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % LFO 2
            audioPluginParameter('LFO2Shape',                   'DisplayName', 'LFO2 Shape',                'Layout',[19,1],     'Label','',        'Mapping',{'enum','SIN', 'TRI', 'SQR', 'SAW', 'S&H'},           'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('LFO2RateHz',                  'DisplayName', 'Rate',                      'Layout',[19,2],     'Label','Hz',      'Mapping',{'log', 0.01, 20},                                    'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('LFO2RateSync',                'DisplayName', 'Rate',                      'Layout',[19,3],     'Label','',        'Mapping',{'enum','1', '1/2', '1/4', '1/8', '1/16', '1/32'},    'DisplayNameLocation', 'Above',     'Style', 'dropdown'),...
            audioPluginParameter('LFO2RateType',                'DisplayName', 'Time Mode',                 'Layout',[19,4],     'Label','',        'Mapping',{'enum','Sync', 'Hz'},                                'DisplayNameLocation', 'Above',     'Style', 'vtoggle'),...
            audioPluginParameter('LFO2Depth',                   'DisplayName', 'Depth',                     'Layout',[19,5],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Modulace
            ... % Přímá větev
            audioPluginParameter('ModDirectLFO1Pan',            'DisplayName', 'Pan (LFO1)',                'Layout',[4,15],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('ModDirectLFO2Pan',            'DisplayName', 'Pan (LFO2)',                'Layout',[4,16],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Pásmo 1    
            audioPluginParameter('ModB1LFO1Cutoff',             'DisplayName', 'Cutoff (LFO1)',             'Layout',[6,13],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('ModB1LFO2Cutoff',             'DisplayName', 'Cutoff (LFO2)',             'Layout',[6,14],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('ModB1LFO1Pan',                'DisplayName', 'Pan (LFO1)',                'Layout',[6,15],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('ModB1LFO2Pan',                'DisplayName', 'Pan (LFO2)',                'Layout',[6,16],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('ModB1LFO1Delay',              'DisplayName', 'Delay (LFO1)',              'Layout',[6,17],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('ModB1LFO2Delay',              'DisplayName', 'Delay (LFO2)',              'Layout',[6,18],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            ... % Pásmo 2
            audioPluginParameter('ModB2LFO1Cutoff',                                                         'Layout',[8,13],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB2LFO2Cutoff',                                                         'Layout',[8,14],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB2LFO1Pan',                                                            'Layout',[8,15],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB2LFO2Pan',                                                            'Layout',[8,16],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB2LFO1Delay',                                                          'Layout',[8,17],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB2LFO2Delay',                                                          'Layout',[8,18],     'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            ... % Pásmo 3
            audioPluginParameter('ModB3LFO1Cutoff',                                                         'Layout',[10,13],    'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB3LFO2Cutoff',                                                         'Layout',[10,14],    'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB3LFO1Pan',                                                            'Layout',[10,15],    'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB3LFO2Pan',                                                            'Layout',[10,16],    'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB3LFO1Delay',                                                          'Layout',[10,17],    'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB3LFO2Delay',                                                          'Layout',[10,18],    'Label','%',       'Mapping',{'lin',0, 100},                                       'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            ... % Pásmo 4
            audioPluginParameter('ModB4LFO1Cutoff',                                                         'Layout',[12,13],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB4LFO2Cutoff',                                                         'Layout',[12,14],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB4LFO1Pan',                                                            'Layout',[12,15],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB4LFO2Pan',                                                            'Layout',[12,16],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB4LFO1Delay',                                                          'Layout',[12,17],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB4LFO2Delay',                                                          'Layout',[12,18],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            ... % Pásmo 5
            audioPluginParameter('ModB5LFO1Cutoff',                                                         'Layout',[14,13],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB5LFO2Cutoff',                                                         'Layout',[14,14],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB5LFO1Pan',                                                            'Layout',[14,15],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB5LFO2Pan',                                                            'Layout',[14,16],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB5LFO1Delay',                                                          'Layout',[14,17],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            audioPluginParameter('ModB5LFO2Delay',                                                          'Layout',[14,18],     'Label','%',       'Mapping',{'lin',0, 100},                                      'DisplayNameLocation', 'None',      'Style', 'rotaryknob'),...
            ... % Rozsahy modulace
            audioPluginParameter('ModCutoffRange',              'DisplayName', 'Cutoff Mod Range',          'Layout',[17,13],     'Label','Hz',      'Mapping',{'lin',10, 5000},                                     'DisplayNameLocation', 'Above',     'Style', 'rotaryknob'),...
            audioPluginParameter('ModDelayRange',               'DisplayName', 'Delay Mod Range',           'Layout',[17,17],     'Label','ms',      'Mapping',{'lin',1.5, 200},                                      'DisplayNameLocation', 'Above',     'Style', 'rotaryknob')...
            );
    end
    methods
        function out = process(p,in)
            % Získání hodnoty vzorkovacího kmitočtu pluginu:
            fs = p.getSampleRate();

            % Vymazání obsahu kruhového bufferu všech pásem:
            if p.PluginClearBuffers
                p.Band1Buffer = zeros(size(p.Band1Buffer));
                p.Band2Buffer = zeros(size(p.Band2Buffer));
                p.Band3Buffer = zeros(size(p.Band3Buffer));
                p.Band4Buffer = zeros(size(p.Band4Buffer));
                p.Band5Buffer = zeros(size(p.Band5Buffer));
            end


            % Zápis parametrů uživatelského prostředí do struktur:
            % Zdrojový kód se tímto sice poměrně hodně prodlouží, nicméně
            % dojde k velkému zlepšení čitelnosti, jelikož se výrazně sníží
            % počet vstupních argumentů dílčích funkcí. Některé parametry
            % jsou stále předávány přímo.
            LFO1Param.shape = p.LFO1Shape;
            LFO1Param.fHz = p.LFO1RateHz;
            LFO1Param.fSync = p.LFO1RateSync;
            LFO1Param.rateType = p.LFO1RateType;
            LFO1Param.depth = p.LFO1Depth;
            LFO1Param.phase = p.LFO1Phase;
            LFO1Param.bufferLength = length(in);
            LFO1Param.BPM = p.PluginBPM;
            LFO1Param.noiseIndex = p.LFO1NoiseIndex;
            LFO1Param.noiseValue = p.LFO1NoiseValue;

            LFO2Param.shape = p.LFO2Shape;
            LFO2Param.fHz = p.LFO2RateHz;
            LFO2Param.fSync = p.LFO2RateSync;
            LFO2Param.rateType = p.LFO2RateType;
            LFO2Param.depth = p.LFO2Depth;
            LFO2Param.phase = p.LFO2Phase;
            LFO2Param.bufferLength = length(in);
            LFO2Param.BPM = p.PluginBPM;
            LFO2Param.noiseIndex = p.LFO2NoiseIndex;
            LFO2Param.noiseValue = p.LFO2NoiseValue;

            Band1Param.Enable = p.Band1Enable;                      Band2Param.Enable = p.Band2Enable;                      Band3Param.Enable = p.Band3Enable;                      Band4Param.Enable = p.Band4Enable;                      Band5Param.Enable = p.Band5Enable;                  
            Band1Param.FilterType = p.Band1FilterType;              Band2Param.FilterType = p.Band2FilterType;              Band3Param.FilterType = p.Band3FilterType;              Band4Param.FilterType = p.Band4FilterType;              Band5Param.FilterType = p.Band5FilterType;          
            Band1Param.FilterCutoff = p.Band1FilterCutoff;          Band2Param.FilterCutoff = p.Band2FilterCutoff;          Band3Param.FilterCutoff = p.Band3FilterCutoff;          Band4Param.FilterCutoff = p.Band4FilterCutoff;          Band5Param.FilterCutoff = p.Band5FilterCutoff;      
            Band1Param.FilterQ = p.Band1FilterQ;                    Band2Param.FilterQ = p.Band2FilterQ;                    Band3Param.FilterQ = p.Band3FilterQ;                    Band4Param.FilterQ = p.Band4FilterQ;                    Band5Param.FilterQ = p.Band5FilterQ;                
            Band1Param.FilterGain = p.Band1FilterGain;              Band2Param.FilterGain = p.Band2FilterGain;              Band3Param.FilterGain = p.Band3FilterGain;              Band4Param.FilterGain = p.Band4FilterGain;              Band5Param.FilterGain = p.Band5FilterGain;          
            Band1Param.FilterOrder = p.Band1FilterOrder;            Band2Param.FilterOrder = p.Band2FilterOrder;            Band3Param.FilterOrder = p.Band3FilterOrder;            Band4Param.FilterOrder = p.Band4FilterOrder;            Band5Param.FilterOrder = p.Band5FilterOrder;        
            Band1Param.FilterConditions = p.Band1FilterConditions;  Band2Param.FilterConditions = p.Band2FilterConditions;  Band3Param.FilterConditions = p.Band3FilterConditions;  Band4Param.FilterConditions = p.Band4FilterConditions;  Band5Param.FilterConditions = p.Band5FilterConditions;
            Band1Param.Gain = p.Band1Gain;                          Band2Param.Gain = p.Band2Gain;                          Band3Param.Gain = p.Band3Gain;                          Band4Param.Gain = p.Band4Gain;                          Band5Param.Gain = p.Band5Gain;                      
            Band1Param.Delay = p.Band1Delay;                        Band2Param.Delay = p.Band2Delay;                        Band3Param.Delay = p.Band3Delay;                        Band4Param.Delay = p.Band4Delay;                        Band5Param.Delay = p.Band5Delay;                    
            Band1Param.Feedback = p.Band1Feedback;                  Band2Param.Feedback = p.Band2Feedback;                  Band3Param.Feedback = p.Band3Feedback;                  Band4Param.Feedback = p.Band4Feedback;                  Band5Param.Feedback = p.Band5Feedback;              
            Band1Param.Feedforward = p.Band1Feedforward;            Band2Param.Feedforward = p.Band2Feedforward;            Band3Param.Feedforward = p.Band3Feedforward;            Band4Param.Feedforward = p.Band4Feedforward;            Band5Param.Feedforward = p.Band5Feedforward;
            Band1Param.Buffer = p.Band1Buffer;                      Band2Param.Buffer = p.Band2Buffer;                      Band3Param.Buffer = p.Band3Buffer;                      Band4Param.Buffer = p.Band4Buffer;                      Band5Param.Buffer = p.Band5Buffer;
            Band1Param.Dpw = p.Band1Dpw;                            Band2Param.Dpw = p.Band2Dpw;                            Band3Param.Dpw = p.Band3Dpw;                            Band4Param.Dpw = p.Band4Dpw;                            Band5Param.Dpw = p.Band5Dpw;

            ModParam.CutoffRange = p.ModCutoffRange;
            ModParam.DelayRange = p.ModDelayRange;
            ModDirectParam.LFO1Pan  = p.ModDirectLFO1Pan;
            ModDirectParam.LFO2Pan  = p.ModDirectLFO2Pan;
            ModB1Param.LFO1Cutoff = p.ModB1LFO1Cutoff;      ModB2Param.LFO1Cutoff = p.ModB2LFO1Cutoff;      ModB3Param.LFO1Cutoff = p.ModB3LFO1Cutoff;      ModB4Param.LFO1Cutoff = p.ModB4LFO1Cutoff;      ModB5Param.LFO1Cutoff = p.ModB5LFO1Cutoff;
            ModB1Param.LFO2Cutoff = p.ModB1LFO2Cutoff;      ModB2Param.LFO2Cutoff = p.ModB2LFO2Cutoff;      ModB3Param.LFO2Cutoff = p.ModB3LFO2Cutoff;      ModB4Param.LFO2Cutoff = p.ModB4LFO2Cutoff;      ModB5Param.LFO2Cutoff = p.ModB5LFO2Cutoff;
            ModB1Param.LFO1Pan = p.ModB1LFO1Pan;            ModB2Param.LFO1Pan = p.ModB2LFO1Pan;            ModB3Param.LFO1Pan = p.ModB3LFO1Pan;            ModB4Param.LFO1Pan = p.ModB4LFO1Pan;            ModB5Param.LFO1Pan = p.ModB5LFO1Pan;
            ModB1Param.LFO2Pan = p.ModB1LFO2Pan;            ModB2Param.LFO2Pan = p.ModB2LFO2Pan;            ModB3Param.LFO2Pan = p.ModB3LFO2Pan;            ModB4Param.LFO2Pan = p.ModB4LFO2Pan;            ModB5Param.LFO2Pan = p.ModB5LFO2Pan;
            ModB1Param.LFO1Delay = p.ModB1LFO1Delay;        ModB2Param.LFO1Delay = p.ModB2LFO1Delay;        ModB3Param.LFO1Delay = p.ModB3LFO1Delay;        ModB4Param.LFO1Delay = p.ModB4LFO1Delay;        ModB5Param.LFO1Delay = p.ModB5LFO1Delay;
            ModB1Param.LFO2Delay = p.ModB1LFO2Delay;        ModB2Param.LFO2Delay = p.ModB2LFO2Delay;        ModB3Param.LFO2Delay = p.ModB3LFO2Delay;        ModB4Param.LFO2Delay = p.ModB4LFO2Delay;        ModB5Param.LFO2Delay = p.ModB5LFO2Delay;

            % Výpočet signálů LFO:
            [LFO1Signal, p.LFO1Phase, p.LFO1NoiseIndex, p.LFO1NoiseValue] = lfo(fs, LFO1Param);
            [LFO2Signal, p.LFO2Phase, p.LFO2NoiseIndex, p.LFO2NoiseValue] = lfo(fs, LFO2Param);

            % Doplnění vypočtených signálů LFO do struktury:
            ModParam.LFO1Signal = LFO1Signal;
            ModParam.LFO2Signal = LFO2Signal;

            % Vstupní zesílení:
            input = 10^(p.PluginInputGain ./ 20) * in;

            % Filtrace, zpoždění a panorama každého pásma:
            input = panorama(input, p.DirectPan, ModDirectParam, ModParam);
            if Band1Param.Enable
                [Band1Signal, p.Band1FilterConditions] = freqFilter(input, fs, Band1Param, ModB1Param, ModParam);
                [Band1Signal, p.Band1Buffer, p.Band1Dpw] = delay(Band1Signal, fs, Band1Param, ModB1Param, ModParam);
                Band1Signal = panorama(Band1Signal, p.Band1Pan, ModB1Param, ModParam);
            else
                Band1Signal = zeros(size(in));
            end
            if p.Band2Enable
                [Band2Signal, p.Band2FilterConditions] = freqFilter(input, fs, Band2Param, ModB2Param, ModParam);
                [Band2Signal, p.Band2Buffer, p.Band2Dpw] = delay(Band2Signal, fs, Band2Param, ModB2Param, ModParam);
                Band2Signal = panorama(Band2Signal, p.Band2Pan, ModB2Param, ModParam);
            else
                Band2Signal = zeros(size(in));
            end
            if p.Band3Enable
                [Band3Signal, p.Band3FilterConditions] = freqFilter(input, fs, Band3Param, ModB3Param, ModParam);
                [Band3Signal, p.Band3Buffer, p.Band3Dpw] = delay(Band3Signal, fs, Band3Param, ModB3Param, ModParam);
                Band3Signal = panorama(Band3Signal, p.Band3Pan, ModB3Param, ModParam);
            else
                Band3Signal = zeros(size(in));
            end
            if p.Band4Enable
                [Band4Signal, p.Band4FilterConditions] = freqFilter(input, fs, Band4Param, ModB4Param, ModParam);
                [Band4Signal, p.Band4Buffer, p.Band4Dpw] = delay(Band4Signal, fs, Band4Param, ModB4Param, ModParam);
                Band4Signal = panorama(Band4Signal, p.Band4Pan, ModB4Param, ModParam);
            else
                Band4Signal = zeros(size(in));
            end
            if p.Band5Enable
                [Band5Signal, p.Band5FilterConditions] = freqFilter(input, fs, Band5Param, ModB5Param, ModParam);
                [Band5Signal, p.Band5Buffer, p.Band5Dpw] = delay(Band5Signal, fs, Band5Param, ModB5Param, ModParam);
                 Band5Signal = panorama(Band5Signal, p.Band5Pan, ModB5Param, ModParam);
            else
                Band5Signal = zeros(size(in));
            end

            % Sečtení všech pásem:
            out = (p.DirectEnable * 10^(p.DirectGain ./ 20)) * input...
                + (p.Band1Enable * 10^(p.Band1Gain ./ 20)) * Band1Signal...
                + (p.Band2Enable * 10^(p.Band2Gain ./ 20)) * Band2Signal...
                + (p.Band3Enable * 10^(p.Band3Gain ./ 20)) * Band3Signal...
                + (p.Band4Enable * 10^(p.Band4Gain ./ 20)) * Band4Signal...
                + (p.Band5Enable * 10^(p.Band5Gain ./ 20)) * Band5Signal;

            % Výstupní zesílení:
            out = 10^(p.PluginOutputGain ./ 20) * out;

            % Smíchání se vstupním signálem:
            out = (p.PluginMix / 100) * out + ((100 - p.PluginMix) / 100) * in;
        end
    end
end